services:
  psql:
    image: postgres:13-alpine
    container_name: psql
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      - DJANGO_ENV=production
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@psql:5432/${DB_NAME}
    image: projeto:latest
    container_name: container_projeto
    restart: always
    env_file:
      - .env
    depends_on:
      - psql
    command: gunicorn projeto.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/app/static
      - ./media:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
