version: '3.9'

services:
  psql:
    image: postgres:13-alpine
    container_name: psql
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - django-net

  web:
    build: .
    image: projeto:latest
    container_name: container_projeto
    restart: always
    env_file:
      - .env
    depends_on:
      - psql
    environment:
      - DJANGO_ENV=production
      # Mantive DATABASE_URL, importante para Django reconhecer o Postgres
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@psql:5432/${DB_NAME}
    command: gunicorn projeto.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    networks:
      - django-net
      - nginx-net

    # 🔹 Sugestão mínima para build CSS automático (opcional)
    # Você poderia adicionar um volume com o script build_css.py
    # e rodar o build antes do Gunicorn se quiser automatizar:
    # entrypoint: sh -c "python build_css.py && gunicorn projeto.wsgi:application --bind 0.0.0.0:8000"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web
    networks:
      - nginx-net

volumes:
  postgres_data:

networks:
  django-net:
    driver: bridge
  nginx-net:
    driver: bridge