# Generated by Django 5.1.1 on 2025-03-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela1',
            name='campo3',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1),
        ),
    ]
