# Generated by Django 5.1.1 on 2025-04-05 15:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0002_alter_tabela1_campo3'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaSis2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100)),
                ('campo2', models.IntegerField(help_text='Exemplo de IntegerField.', verbose_name='Número Inteiro')),
            ],
        ),
        migrations.AlterField(
            model_name='tabela1',
            name='campo4',
            field=models.BooleanField(default=False, verbose_name='Campo Booleano'),
        ),
        migrations.AlterField(
            model_name='tabela1',
            name='campo5',
            field=models.TextField(verbose_name='Campo de Texto Longo'),
        ),
        migrations.CreateModel(
            name='TabelaSis1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100, verbose_name='campo1: Campo de Texto Curto')),
                ('campo2', models.TextField(verbose_name='campo2: Campo de Texto Longo')),
                ('campo3', models.IntegerField(verbose_name='campo3: Número Inteiro')),
                ('campo4', models.FloatField(verbose_name='campo4: Número Decimal')),
                ('campo5', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='campo5: Número Decimal Precisão Fixa')),
                ('campo6', models.BooleanField(default=False, verbose_name='campo6: Campo Booleano')),
                ('campo7', models.DateField(verbose_name='campo7: Data')),
                ('campo8', models.TimeField(verbose_name='campo8: Hora')),
                ('campo9', models.DateTimeField(verbose_name='campo9: Data e Hora')),
                ('campo10', models.EmailField(max_length=254, verbose_name='campo10: E-mail')),
                ('campo11', models.URLField(verbose_name='campo11: URL')),
                ('campo12', models.SlugField(verbose_name='campo12: Slug')),
                ('campo13', models.UUIDField(verbose_name='campo13: UUID')),
                ('campo14', models.BinaryField(verbose_name='campo14: Binário')),
                ('campo15', models.ImageField(upload_to='imagens/', verbose_name='campo15: Imagem')),
                ('campo16', models.FileField(upload_to='arquivos/', verbose_name='campo16: Arquivo')),
                ('campo17', models.CharField(help_text='Este campo deve ter um valor único.', max_length=50, unique=True, verbose_name='campo17: Campo Único')),
                ('campo18', models.IntegerField(default=0, help_text='Este campo tem um valor padrão.', verbose_name='campo18: Campo com Valor Padrão')),
                ('campo19', models.CharField(choices=[('A', 'Opção A'), ('B', 'Opção B'), ('C', 'Opção C')], help_text='Escolha entre as opções disponíveis.', max_length=20, verbose_name='campo18: Campo com Choices')),
                ('campo20', models.PositiveIntegerField(help_text='Apenas valores positivos são permitidos.', verbose_name='campo20: Número Positivo')),
                ('campo21', models.DecimalField(decimal_places=2, help_text='Insira um número entre 0 e 100.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='campo21: Número entre 0 e 100')),
                ('Campo22', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relacionado', to='aplicativo.tabelasis2')),
            ],
            options={
                'verbose_name': 'Exemplo de Model',
                'verbose_name_plural': 'campo22: Exemplos de Models',
                'ordering': ['campo1'],
            },
        ),
    ]
